// @flow
export const SET_COMPANY_DATA: 'SET_COMPANY_DATA' = 'SET_COMPANY_DATA';
export const UPDATE_COMPANY_DATA: 'UPDATE_COMPANY_DATA' = 'UPDATE_COMPANY_DATA';
export const DELETE_COMPANY: 'DELETE_COMPANY' = 'DELETE_COMPANY';
